### ISSUE TITLE
1.20 build

### ISSUE THREAD

**Issue by OojinJi** [Loyal0713/DisableMobGriefing#1]
The 1.20 build still requires the 1.12 api

**Comment by Loyal0713** [comment]
Sorry for delay, but nice catch. Was going through these pretty quickly, figured I'd miss something. Working on now, should be a quick fix

**Comment by Loyal0713** [comment]
Updated **ALL** branches since they all referenced 1.12 API, building and submitting updated JARs to CurseForge and Modrinth

**Comment by Loyal0713** [comment]
All branches are updated with latest code and updated Modrinth (Curseforge only has 1.12)
